language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
test:
  $(shell export PYTHONPATH=$PYTHONPATH:$(pwd))
  python app/tests/app-test.py
